name: CDK Deploy On Bucket changes

on:
  workflow_dispatch:
    paths:
      - www/**
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run lint
      - run: npm run build --if-present
      - run: npm test
      - name: Create .env.development file
        run: |
              touch .env.development
              echo "CDK_DEPLOY_ACCOUNT=${{ secrets.AWS_DEPLOY_ACCOUNT }}" >> .env.development
              echo "CDK_DEPLOY_REGION=us-east-1" >> .env.development
              echo "BUCKET_NAME=${{ secrets.DEV_BUCKET_NAME }}" >> .env.development
              echo "DOMAIN_NAME=${{ secrets.DEV_DOMAIN_NAME }}" >> .env.development
      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "deploy"
          cdk_stack: "--all"
          cdk_args: "--require-approval never -c environment=development"
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
  
  test:
    needs: deploy
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node14.17.0-chrome91-ff89
      options: --user 1001
    strategy:
      matrix:
        browser: [chrome, firefox]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      # Run all cypress tests.
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          wait-on: ${{ secrets.DEV_BASE_URL }}
          wait-on-timeout: 10
          browser: ${{ matrix.browser }}
        env:
          CYPRESS_BASE_URL: ${{ secrets.DEV_BASE_URL }}
        
  destroy:
    needs: [deploy, test]
    if: always() && needs.deploy.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create .env.development file
        run: |
              touch .env.development
              echo "CDK_DEPLOY_ACCOUNT=${{ secrets.AWS_DEPLOY_ACCOUNT }}" >> .env.development
              echo "CDK_DEPLOY_REGION=us-east-1" >> .env.development
              echo "BUCKET_NAME=${{ secrets.DEV_BUCKET_NAME }}" >> .env.development
              echo "DOMAIN_NAME=${{ secrets.DEV_DOMAIN_NAME }}" >> .env.development
      - name: cdk destroy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "destroy"
          cdk_stack: "--all"
          cdk_args: "--require-approval never -c environment=development"
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
