name: CDK Deploy (staging first with tests)

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - www/**

env:
  STAGING_DOMAIN_NAME: michaelbudnick.dev
  STAGING_BASE_URL: https://www.michaelbudnick.dev/

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run lint
      - run: npm run build --if-present
      - run: npm test
      - name: Create .env.staging file
        run: |
              touch .env.staging
              echo "CDK_DEPLOY_ACCOUNT=${{ secrets.AWS_DEPLOY_ACCOUNT }}" >> .env.staging
              echo "CDK_DEPLOY_REGION=us-east-1" >> .env.staging
              echo "BUCKET_NAME=${{ secrets.DEV_BUCKET_NAME }}" >> .env.staging
              echo "DOMAIN_NAME=${{ env.STAGING_DOMAIN_NAME }}" >> .env.staging
      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "deploy"
          cdk_args: "--require-approval never -c environment=staging"
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"

  sync-staging:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Sync files to S3 bucket
      run: |
        aws s3 sync www s3://${{ secrets.DEV_BUCKET_NAME }} --delete
  
  test-staging:
    needs: sync-staging
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node14.17.0-chrome91-ff89
      options: --user 1001
    strategy:
      matrix:
        browser: [chrome, firefox]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      # Run all cypress tests.
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: false
          config-file: cypress.config.ts
          wait-on: ${{ env.STAGING_BASE_URL }}
          wait-on-timeout: 10
          browser: ${{ matrix.browser }}
        env:
          CYPRESS_BASE_URL: ${{ env.STAGING_BASE_URL }}
        
  destroy-staging:
    needs: [deploy-staging, test-staging]
    if: always() && needs.deploy-staging.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create .env.staging file
        run: |
              touch .env.staging
              echo "CDK_DEPLOY_ACCOUNT=${{ secrets.AWS_DEPLOY_ACCOUNT }}" >> .env.staging
              echo "CDK_DEPLOY_REGION=us-east-1" >> .env.staging
              echo "BUCKET_NAME=${{ env.STAGING_BUCKET_NAME }}" >> .env.staging
              echo "DOMAIN_NAME=${{ env.STAGING_DOMAIN_NAME }}" >> .env.staging
      - name: cdk destroy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "destroy"
          cdk_args: "--force -c environment=staging"
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"

  deploy-prod:
    runs-on: ubuntu-latest
    needs: test-staging
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - name: Create .env.production file
        run: |
              touch .env.production
              echo "CDK_DEPLOY_ACCOUNT=${{ secrets.AWS_DEPLOY_ACCOUNT }}" >> .env.production
              echo "CDK_DEPLOY_REGION=us-east-1" >> .env.production
              echo "BUCKET_NAME=${{ secrets.PROD_BUCKET_NAME }}" >> .env.production
              echo "DOMAIN_NAME=${{ env.PROD_DOMAIN_NAME }}" >> .env.production
      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "deploy"
          cdk_args: "--require-approval never -c environment=production"
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
  
  sync-prod:
    runs-on: ubuntu-latest
    needs: deploy-prod
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Sync files to S3 bucket
      run: |
        aws s3 sync www s3://${{ secrets.PROD_BUCKET_NAME }} --delete