name: CDK Deploy (staging first with Cypress tests)

on:
  workflow_dispatch:
    paths:
      - www/**
    branches: ["main"]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run lint
      - run: npm run build --if-present
      - run: npm test
      - name: Create .env.staging file
        run: |
              touch .env.staging
              echo "CDK_DEPLOY_ACCOUNT=${{ secrets.AWS_DEPLOY_ACCOUNT }}" >> .env.staging
              echo "CDK_DEPLOY_REGION=us-east-1" >> .env.staging
              echo "BUCKET_NAME=${{ secrets.DEV_BUCKET_NAME }}" >> .env.staging
              echo "DOMAIN_NAME=${{ secrets.DEV_DOMAIN_NAME }}" >> .env.staging
      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "deploy"
          cdk_args: "--require-approval never -c environment=staging"
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
  
  test-staging:
    needs: deploy-dev
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node14.17.0-chrome91-ff89
      options: --user 1001
    strategy:
      matrix:
        browser: [chrome, firefox]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      # Run all cypress tests.
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: false
          config-file: cypress.config.ts
          wait-on: ${{ secrets.DEV_BASE_URL }}
          wait-on-timeout: 10
          browser: ${{ matrix.browser }}
        env:
          CYPRESS_BASE_URL: ${{ secrets.DEV_BASE_URL }}
        
  destroy-dev:
    needs: [deploy-dev, test-staging]
    if: always() && needs.deploy-dev.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create .env.staging file
        run: |
              touch .env.staging
              echo "CDK_DEPLOY_ACCOUNT=${{ secrets.AWS_DEPLOY_ACCOUNT }}" >> .env.staging
              echo "CDK_DEPLOY_REGION=us-east-1" >> .env.staging
              echo "BUCKET_NAME=${{ secrets.DEV_BUCKET_NAME }}" >> .env.staging
              echo "DOMAIN_NAME=${{ secrets.DEV_DOMAIN_NAME }}" >> .env.staging
      - name: cdk destroy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "destroy"
          cdk_args: "--force -c environment=staging"
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"

  deploy-prod:
    runs-on: ubuntu-latest
    needs: test-staging
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - name: Create .env.production file
        run: |
              touch .env.production
              echo "CDK_DEPLOY_ACCOUNT=${{ secrets.AWS_DEPLOY_ACCOUNT }}" >> .env.production
              echo "CDK_DEPLOY_REGION=us-east-1" >> .env.production
              echo "BUCKET_NAME=${{ secrets.PROD_BUCKET_NAME }}" >> .env.production
              echo "DOMAIN_NAME=${{ secrets.PROD_DOMAIN_NAME }}" >> .env.production
      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "deploy"
          cdk_args: "--require-approval never -c environment=production"
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"