name: Cypress Testing every 6 hours

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  test-prod:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node14.17.0-chrome91-ff89
      options: --user 1001
    strategy:
      matrix:
        browser: [chrome, firefox]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - run: npm ci
      - run: npm run build --if-present
      # Run all cypress tests.
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: false
          config-file: cypress.config.ts
          browser: ${{ matrix.browser }}
        env:
          CYPRESS_BASE_URL: "https://${{ secrets.PROD_DOMAIN_NAME }}/"
          # DEBUG: '@cypress/github-action'
