name: Update Dependencies and Audit

on:
  schedule:
    - cron: '0 5 * * 5' # Run every Friday at midnight EST

jobs:
  update-and-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install jq

      - name: Save original vulnerabilities count
        id: original_vulnerabilities
        run: |
          ORIGINAL_CRITICAL_VULNERABILITIES=$(npm audit --json | jq -r '.metadata.vulnerabilities | .critical')
          ORIGINAL_HIGH_VULNERABILITIES=$(npm audit --json | jq -r '.metadata.vulnerabilities | .high')
          echo "Original critical vulnerabilities count: $ORIGINAL_CRITICAL_VULNERABILITIES"
          echo "Original high vulnerabilities count: $ORIGINAL_HIGH_VULNERABILITIES"

      - name: Update dependencies
        run: |
          npm install -g npm-check-updates
          npx npm-check-updates -u
          npm install

      - name: Audit dependencies
        run: npm audit

      - name: Check for vulnerabilities
        run: |
          CURRENT_CRITICAL_VULNERABILITIES=$(npm audit --json | jq -r '.metadata.vulnerabilities | .critical')
          CURRENT_HIGH_VULNERABILITIES=$(npm audit --json | jq -r '.metadata.vulnerabilities | .high')
          echo "Current critical vulnerabilities count: $CURRENT_CRITICAL_VULNERABILITIES"
          echo "Current high vulnerabilities count: $CURRENT_HIGH_VULNERABILITIES"
          if [ "$CURRENT_CRITICAL_VULNERABILITIES" -le "$ORIGINAL_CRITICAL_VULNERABILITIES" ] && [ "$CURRENT_HIGH_VULNERABILITIES" -le "$ORIGINAL_HIGH_VULNERABILITIES" ]; then
            echo "No new critical or high vulnerabilities found, or the count is equal."
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'actions@github.com'
            git add package.json package-lock.json
            git commit -m "Update dependencies"
            git push
          else
            echo "New vulnerabilities found. Please review and update manually."
            exit 1
          fi
